// Generated by scripts/i18n_build.mjs. Do not edit by hand.
//
// Part of the generated src/ui/i18n.resolved.generated/ directory: one dense
// locale slice per file (each `: EnTranslations` = typeof en, so tsc red-fails a
// missing or renamed key), a back-compat barrel (index.ts) that re-exports every
// slice and assembles the runtime `translations` map, per-locale lazy loaders
// (loaders.ts), and the pending set (pending.ts). Regenerate with
// `npm run i18n:build` (also wired into `npm run build` and `pretest`).
// Reproducibility is checked by tests/i18n_resolved_equivalence.test.ts.

export const pending: Record<string, readonly string[]> = {
  "es": [
    "hudChrome.crafting.comboRequirementUnmet",
    "hudChrome.discord.roleTag.coredevs",
    "hudChrome.mobile.dailyRewards"
  ],
  "es_ES": [
    "hudChrome.crafting.comboRequirementUnmet",
    "hudChrome.discord.roleTag.coredevs",
    "hudChrome.mobile.dailyRewards"
  ],
  "fr_FR": [
    "hudChrome.crafting.comboRequirementUnmet",
    "hudChrome.discord.roleTag.coredevs",
    "hudChrome.mobile.dailyRewards"
  ],
  "fr_CA": [
    "hudChrome.crafting.comboRequirementUnmet",
    "hudChrome.discord.roleTag.coredevs",
    "hudChrome.mobile.dailyRewards"
  ],
  "en_CA": [],
  "it_IT": [
    "hudChrome.crafting.comboRequirementUnmet",
    "hudChrome.discord.roleTag.coredevs",
    "hudChrome.mobile.dailyRewards"
  ],
  "de_DE": [
    "hudChrome.crafting.comboRequirementUnmet",
    "hudChrome.discord.roleTag.coredevs",
    "hudChrome.mobile.dailyRewards"
  ],
  "zh_CN": [
    "hudChrome.discord.roleTag.coredevs"
  ],
  "zh_TW": [
    "hudChrome.discord.roleTag.coredevs"
  ],
  "ko_KR": [
    "hudChrome.discord.roleTag.coredevs"
  ],
  "ja_JP": [
    "hudChrome.discord.roleTag.coredevs"
  ],
  "pt_BR": [
    "hudChrome.crafting.comboRequirementUnmet",
    "hudChrome.discord.roleTag.coredevs",
    "hudChrome.mobile.dailyRewards"
  ],
  "ru_RU": [
    "hudChrome.discord.roleTag.coredevs"
  ],
  "cs_CZ": [
    "hudChrome.crafting.comboRequirementUnmet",
    "hudChrome.discord.roleTag.coredevs",
    "hudChrome.mobile.actionPageIndicator",
    "hudChrome.mobile.actionPageToggle",
    "hudChrome.mobile.actionRing",
    "hudChrome.mobile.dailyRewards",
    "hudChrome.mobile.hotbarPage",
    "hudChrome.mobile.hotbarPageAria",
    "hudChrome.mobile.spellbookPageLabel",
    "hudChrome.mobile.targetCycle",
    "hudChrome.mobile.targetCycleShort",
    "hudChrome.options.mobileCameraJoystick",
    "hudChrome.options.mobileLeftHanded"
  ],
  "nl_NL": [
    "hudChrome.crafting.comboRequirementUnmet",
    "hudChrome.discord.roleTag.coredevs",
    "hudChrome.mobile.dailyRewards"
  ],
  "pl_PL": [
    "hudChrome.crafting.comboRequirementUnmet",
    "hudChrome.discord.roleTag.coredevs",
    "hudChrome.mobile.dailyRewards"
  ],
  "id_ID": [
    "hudChrome.crafting.comboRequirementUnmet",
    "hudChrome.discord.roleTag.coredevs",
    "hudChrome.mobile.dailyRewards"
  ],
  "tr_TR": [
    "hudChrome.crafting.comboRequirementUnmet",
    "hudChrome.discord.roleTag.coredevs",
    "hudChrome.mobile.dailyRewards"
  ],
  "sv_SE": [
    "hudChrome.crafting.comboRequirementUnmet",
    "hudChrome.discord.roleTag.coredevs",
    "hudChrome.mobile.dailyRewards"
  ],
  "vi_VN": [
    "hudChrome.crafting.comboRequirementUnmet",
    "hudChrome.discord.roleTag.coredevs",
    "hudChrome.mobile.dailyRewards"
  ],
  "da_DK": [
    "hudChrome.crafting.comboRequirementUnmet",
    "hudChrome.discord.roleTag.coredevs",
    "hudChrome.mobile.dailyRewards"
  ]
};
